# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - my-eth

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Build native executable with Maven
        run: mvn package -Dnative -Dquarkus.native.container-build=true

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v${{ github.run_number }}
        with:
          login-server: myethregistry.azurecr.io
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build Docker image
        # TODO: append Pull-Request number to image tag
        run: docker build -f src/main/docker/Dockerfile.native -t myethregistry.azurecr.io/myapp:v${{ github.run_number }} .

      - name: Push Docker image to ACR
        run: docker push myethregistry.azurecr.io/myapp:v${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Login to Azure
        uses: azure/login@v${{ github.run_number }}
        with:
          # TODO: create new client & tenant ID, set values in GH secrets
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_56F4A6407CB74731BDC54B8B1CEB1901 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C0590B1E24DC4DA2AB52EEA6C95B7E91 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_33AD0D4B817F4AA4BE4A251189E36D98 }}

      - name: Deploy to Azure Container Instances
        uses: "azure/aci-deploy@v1"
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: my-eth-app
          location: "uae"
